project:
  type: website
  output-dir: docs

website:
  title: "lRoyYul"
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: dash1.qmd
        text: Study1
      - href: dash2.qmd
        text: Study2
      
  site-url: "https;//lRoyYul.github.io/"

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

editor: visual